<?php

namespace FormBM\BMBundle\Repository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
		public function avisEntreprise($id_entreprise){
		return $this->createQueryBuilder('a')
		->select('m.libelle,a.statut')
		->leftJoin('a.entreprise','e')
		->leftJoin('a.motcle','m')
		->Where('a.entreprise =?1')
		->setParameter(1,$id_entreprise)
		->getQuery()
		->getResult();
	}
    public function supAvisEtp($id_entreprise){
        return $this->createQueryBuilder('a')
            ->delete('FormBMBMBundle:Avis a')
            ->Where('a.entreprise =?1')
            ->setParameter(1,$id_entreprise)
            ->getQuery()
            ->execute();
    }
}
