<?php

namespace FormBM\BMBundle\Repository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends \Doctrine\ORM\EntityRepository
{
	public function moyTot($id_entreprise){
		return $this->createQueryBuilder('f')
		->select('avg(f.pourcentage)')
		->Where('f.entreprise =?1')
		->andWhere('f.pourcentage is not null')
		->setParameter(1,$id_entreprise)
		->getQuery()
		->getResult();
	}

	public function moyTheme($id_entreprise){
		return $this->createQueryBuilder('f')
		->select('t.libelle,count(s.id),avg(f.pourcentage) as moy,t.id')
		->leftJoin('f.soustheme','s')
		->leftJoin('s.theme','t')
		->Where('f.entreprise =?1')
		->andWhere('f.pourcentage is not null')
		->groupBy('s.theme')
		->setParameter(1,$id_entreprise)
		->getQuery()
		->getResult();
	}
	public function sousTheme($id_entreprise){
		return $this->createQueryBuilder('f')
		->select('f.pourcentage, t.id, s.libelle')
		->leftJoin('f.soustheme','s')
		->leftJoin('s.theme','t')
        ->Where('f.entreprise =?1')
        ->setParameter(1,$id_entreprise)
		->getQuery()
		->getResult();
	}
    public function supFicheEtp($id_entreprise)
    {
        return $this->createQueryBuilder('f')
            ->delete('FormBMBMBundle:Fiche f')
            ->Where('f.entreprise =?1')
            ->setParameter(1, $id_entreprise)
            ->getQuery()
            ->execute();
    }
    public function verificationST($lib_soustheme,$id_entreprise, $id_theme){
        return $this->createQueryBuilder('f')
            ->select('f')
            ->leftJoin('f.soustheme','s')
            ->Where('f.entreprise =?1')
            ->andWhere('s.libelle =?2')
            ->andWhere('s.theme =?3')
            ->setParameter(1,$id_entreprise)
            ->setParameter(2,$lib_soustheme)
            ->setParameter(3,$id_theme)
            ->getQuery()
            ->getResult();
    }
    public function verifnbTheme($id_entreprise){
        return $this->createQueryBuilder('f')
            ->select('count(distinct s.theme) as nbTheme')
            ->leftJoin('f.soustheme','s')
            ->Where('f.entreprise =?1')
            ->setParameter(1,$id_entreprise)
            ->getQuery()
            ->getResult();
    }
}
