<?php

namespace FormBM\BMBundle\Repository;

/**
 * MotCleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotCleRepository extends \Doctrine\ORM\EntityRepository
{
	    public function listeMotCle()
		{
		return $this->createQueryBuilder('m')
		->select('m')
		->orderBy('m.libelle','ASC');

	}
}
